### ISSUE TITLE
Feature request: watch for apps opening the mic programmatically.

### ISSUE THREAD

**Issue by muffinresearch** [yulrizka/osx-push-to-talk#1]
Some apps (e.g. vidyo, skype) seem to open the mic programmatically when opening a stream.

Would be really nice to add a feature that watches for this. Mute my mic (not open source afaik) has a force mute feature which fixes this problem as it ensure the mic stays muted when in the muted state and it re-mutes if it detects an app changing the mic state. Not how mutemymic does this - whether they just poll or there's a way to actually see an event. 

Interestingly the muted state in the Audio Midi Setup app doesn't appear to change but you can see audio level on the mic input prefs screen.

As a workaround you can hit the ptt key once and that re-mutes the mic - but having this work by default or be an option would be handy.

**Comment by yulrizka** [comment]
Thank you for the input, there is no plan to do this at the moment.
