### ISSUE TITLE
not working in Catalina?

### ISSUE THREAD

**Issue by tbhi** [yulrizka/osx-push-to-talk#11]
seems like it has no affect with fresh install of Catalina - anyone else get this?

**Comment by yulrizka** [comment]
I only have mojave, there it woks fine. Please let me know if any one have any issue

**Comment by yulrizka** [comment]
https://github.com/yulrizka/osx-push-to-talk/pull/14 this PR I think should address it.

**Comment by yulrizka** [comment]
check https://github.com/yulrizka/osx-push-to-talk/releases/tag/v0.1.2
