### ISSUE TITLE
works perfectly, for programmers: could you bind the right control key?

### ISSUE THREAD

**Issue by karsten-mage-market** [yulrizka/osx-push-to-talk#12]
I need the right option key for {} and [] and |.

I never need the right control key,

could you have a version for the right control key as push to talk button? :)

That'd be amazing :D

**Comment by karsten-mage-market** [comment]
https://github.com/yulrizka/osx-push-to-talk/blob/master/PushToTalk/Microphone.swift#L89

**Comment by yulrizka** [comment]
it's now configurable https://github.com/yulrizka/osx-push-to-talk/releases/tag/v0.1.2
