### ISSUE TITLE
Hotkey Issues

### ISSUE THREAD

**Issue by HZ-0Z3R0** [yulrizka/osx-push-to-talk#18]
I can easily change the hotkey. I However, I noticed that if I hold the hotkey the microphone is unmuted, but when I release it the microphone is still unmuted. I tested it on Online Mic Test and with a friend.

**Comment by yulrizka** [comment]
There is recent changes. Have you tried to refresh devices? if you just recently connected a new device (or bluetooth disconnected) it might need to refresh the device.

**Comment by yulrizka** [comment]
closing the issue for now
