### ISSUE TITLE
Remember changed hotkey

### ISSUE THREAD

**Issue by bdeshi** [yulrizka/osx-push-to-talk#19]
The active hotkey can be changed from the app's menu while it's running, but it always reverts back to hotkey 61 when the app is relaunched. Can the custom hotkey be stored as a persistent configuration somewhere please?

**Comment by yulrizka** [comment]
fixed in #23 and released on https://github.com/yulrizka/osx-push-to-talk/releases/tag/v0.1.5

```
$ brew install yulrizka/tap/pushtotalk
```

Read the output of the homebrew to link the file to `/Application`
