### ISSUE TITLE
Feature request: make it possible to change the ptt key

### ISSUE THREAD

**Issue by muffinresearch** [yulrizka/osx-push-to-talk#2]
Right option is quite convenient, but it would be great to add an option to change the key for ptt.

**Comment by IlyaEremin** [comment]
+1

**Comment by IlyaEremin** [comment]
I think we need to change this line and rebuild application: https://github.com/yulrizka/osx-push-to-talk/blob/master/PushToTalk/AppDelegate.swift#L58

**Comment by vcasadei** [comment]
I would like to change it as well. My Keyboard does not have a right option key and it's a pain to have to press the notebook key to use this app.

How could I change it to be the left option key?

**Comment by karsten-mage-market** [comment]
https://github.com/yulrizka/osx-push-to-talk/blob/master/PushToTalk/Microphone.swift#L89

Here it is...

Is there something like a command line args like in C# or Java?

Or how about a environment variable? :)

**Comment by yulrizka** [comment]
I'm open to a PR for a preference window

**Comment by yulrizka** [comment]
There is this PR https://github.com/yulrizka/osx-push-to-talk/pull/14 that will address it will test it soon if I have a catalina machine

**Comment by yulrizka** [comment]
https://github.com/yulrizka/osx-push-to-talk/releases/tag/v0.1.2
