### ISSUE TITLE
Add .app or a .dmg file to GitHub release

### ISSUE THREAD

**Issue by qoomon** [yulrizka/osx-push-to-talk#26]
Would be nice, if you could provide/upload an prebuild `Push to Talk.app` as part of the [GitHub release](https://github.com/yulrizka/osx-push-to-talk/releases/tag/v0.1.5).

**Comment by yulrizka** [comment]
Unfortunately due to #15, pre-built application will not run on Catalina unless the application was sign

**Comment by qoomon** [comment]
Kind of true, however you can also run unsigned applications by explicitly grant permission in `System Preferences` > `Security & Privacy` after you tried to start the app.

**Comment by qoomon** [comment]
Solved by creating GitHub Actions artifacts on master commits see [build action](https://github.com/yulrizka/osx-push-to-talk/actions?query=workflow%3ABuild)
