### ISSUE TITLE
Use Capslock as HotKey

### ISSUE THREAD

**Issue by dennislaumen** [yulrizka/osx-push-to-talk#33]
Is it possible to add support for using Capslock as the HotKey? Or am I misunderstanding the UI and is this already possible?

**Comment by yulrizka** [comment]
It can, but since capslock behave differently than other keys it also don't work very nicely. 

If you really want to use capslock, I suggest mapping it to a different key in OSX Settings > Keyboard > Modifier keys. 
Eg: I map it to control, (but it can also be options, command, escape, etc).

**Comment by dennislaumen** [comment]
@yulrizka Hi Ahmy, thanks for the quick reply. How does the above suggestion help?

I already used that setting to disable the CapsLock key as I use the CapsLock shortcut in other apps (like Discord) to do push to talk. I thought setting this on the OS level would be nicer.
