### ISSUE TITLE
Include compiled app in releases again

### ISSUE THREAD

**Issue by wolfgang42** [yulrizka/osx-push-to-talk#34]
Up through v0.1.2, releases included a .dmg with an unsigned copy of the app. This was convenient because it was possible to install the app without first installing all of XCode and compiling it (albeit with some poking at system settings to get MacOS to be OK with it).

Can you please include the app in the releases again?

I see this was discussed in #26, which @qoomon resolved with a link to the build artifacts; however, the artifact has expired (looks like [the maximum retention period is 90 days](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#artifact-and-log-retention-policy)) and is no longer accessible so this seems unsuitable as a general solution.

BTW, thanks for making this app; it's been a great boon during these times of working from home.

**Comment by yulrizka** [comment]
Thank you for the feedback. I'll try to include an unsigned release again. I've stop uploading to the artifacts since v0.1.2 as you can see, the old artifacts are still there https://github.com/yulrizka/osx-push-to-talk/releases. I'll post an update when it's available again. 

I happy to hear that this small project helps!

**Comment by wolfgang42** [comment]
Any chance you can get to this soon? I'm using 0.1.2, but the double-tap to unmute feature that was added in 0.1.3 would be quite useful.

**Comment by yulrizka** [comment]
Probably not soon, since it's hard for me to get access to a machine where I can compile it. Is the `brew` method on the Readme doesn't work for you?

**Comment by yulrizka** [comment]
let's unified the discussion in #15
