### ISSUE TITLE
Push to talk does not work

### ISSUE THREAD

**Issue by infamousgas** [yulrizka/osx-push-to-talk#35]
This does not seem to work on Google Meet, I have not tried it with other programs. Any thoughts? I am currently running on 11.2.3 macOS Big Sur with an external microphone.

**Comment by yulrizka** [comment]
I don't have any access to Bug Sur yet, but will update once I upgrade.

**Comment by wolfgang42** [comment]
Not sure if this is your problem, but for me Google Meet does some sort of system mute detection that can get confused and keep me muted in the meeting even after PTT unmutes the system audio.

The workaround I've found is: on the screen before you join the meeting
1. turn off PTT
2. unmute the meeting audio
3. click the "Join Meeting" button
4. turn PTT back on

which is more complicated than I'd like, but seems to do the trick.

**Comment by limited107** [comment]
At first time, It works great.
But, after restarting the system, my external usb microphone doesn't work.
The icon is red(on) but, the system can't hear the sound from microphone.

I'm running on 10.15.2 macOS Catalina with an USB microphone. 

I found a workaround solution that if the microphone doesn't work, disconnecting and connecting the microphone then it works great.

**Comment by yulrizka** [comment]
@limited107 when a new external mic is unplug, the list is not updated automatically. There is the option `Refresh Device` and then on the `Device` menu, make sure to select the correct device

**Comment by yulrizka** [comment]
> Not sure if this is your problem, but for me Google Meet does some sort of system mute detection that can get confused and keep me muted in the meeting even after PTT unmutes the system audio.
> 
> The workaround I've found is: on the screen before you join the meeting
> 
>     1. turn off PTT
> 
>     2. unmute the meeting audio
> 
>     3. click the "Join Meeting" button
> 
>     4. turn PTT back on
> 
> 
> which is more complicated than I'd like, but seems to do the trick.

Some time i get this as well with Google Meet. One trick that works for me is after joining the meeting, go to osx settings, (at this point usually pressing the hot key doesn't change the mute state).
After sliding the mic value a little bit it became enabled again.
