### ISSUE TITLE
Brew install requires Xcode

### ISSUE THREAD

**Issue by Pfaufisch** [yulrizka/osx-push-to-talk#37]
As far as I understand the installation instructions, installation of PushToTalk via brew should not require Xcode. However, this is not the case:

```bash
$ brew tap yulrizka/tap
$ brew install pushtotalk
==> Installing pushtotalk from yulrizka/tap
pushtotalk: A full installation of Xcode.app is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
```

Would be great if there was a way to install PushToTalk without Xcode!

**Comment by yulrizka** [comment]
Thanks for the info. This is related to #15. Will close this ticket for now
