### ISSUE TITLE
Black and white icons

### ISSUE THREAD

**Issue by Nitive** [yulrizka/osx-push-to-talk#7]
The icon stands out from a general style of macos icons.
It attracts a lot of attention and I have to quit PushToTalk every time I'm not using it.
![image](https://user-images.githubusercontent.com/6770225/42728063-8e758b6c-87ba-11e8-809d-d18061140ee1.png)
I'm not a designer but I can try to draw different icons.
Will you merge it if I do it and you like it?

**Comment by qoomon** [comment]
That would be really nice, red icon for on air grey for disabled

**Comment by Dimentium** [comment]
> That would be really nice, red icon for on air grey for disabled

Already exist in this fork: https://github.com/ollisulopuisto/osx-push-to-talk
(But `fn` instead `right_option` would be use, or you can revert it and compile app yourself)

**Comment by yulrizka** [comment]
Improvement on the design is always welcome

**Comment by qoomon** [comment]
I think icons from this fork pretty neat https://github.com/ollisulopuisto/osx-push-to-talk

**Comment by yulrizka** [comment]
impelemented in https://github.com/yulrizka/osx-push-to-talk/pull/21

![osx-push-to-talk](https://user-images.githubusercontent.com/117752/96303526-d41f6500-0ffa-11eb-9c0d-d0fd7c0c07af.gif)

```
brew install yulrizka/tap/pushtotalk
```

To get the latest version (notice the homebrew caveat for command to link it to /Application)
