### ISSUE TITLE
Double tap lock/unlock

### ISSUE THREAD

**Issue by marcobazzani** [yulrizka/osx-push-to-talk#8]
Sometimes it's useful to keep it pushed while I can continue to do my work.
Could you add such functionality ?

**Comment by marcobazzani** [comment]
I forked and implemented it in 
https://github.com/marcobazzani/osx-push-to-talk/releases/tag/0.1.0.1

**Comment by yulrizka** [comment]
This is a nice idea, feel free to make a PR

**Comment by mateuspontes** [comment]
@marcobazzani that is a great feature, why not open a PR?

**Comment by yulrizka** [comment]
implemented on #20
